### ISSUE TITLE
Pass symbols in options where strings are used

### ISSUE THREAD

**Issue by lokeshh** [SciRuby/gnuplotrb#7]
Maybe we should also enable passing in symbols in options where strings are passed.

For example
```ruby
Plot.new [dv, with: :histogram], xrange: -1..2, yrange: 0..100
```

**Comment by dilcom** [comment]
Are you totally sure, it doesn't work this way? As far as I remember, GnuplotRB treats symbols just as strings in this case.

**Comment by lokeshh** [comment]
I checked it and its working. Maybe I spelled it wrong while I was trying. Thanks
