### ISSUE TITLE
Pie chart with GnuplotRB

### ISSUE THREAD

**Issue by lokeshh** [SciRuby/gnuplotrb#9]
Are pie chart supported in GnuplotRB?

**Comment by dilcom** [comment]
There is no way to plot pie chart in Gnuplot easily (you may take a look at some tricks given in FAQ http://www.gnuplot.info/faq/faq.html#x1-440004.5), so no, GnuplotRB does not support pie charts.

**Comment by lokeshh** [comment]
Ok. Thanks.
